# Generated by Django 5.1 on 2024-08-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appweb', '0002_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
